# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: WPLNNewscast

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
        
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/wplnnewscast.pem
        chmod 600 ~/.ssh/wplnnewscast.pem

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H wplnnewscast.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/wplnnewscast.pem ubuntu@wplnnewscast.com << 'EOF'
          cd /home/ubuntu/wplnnewscast
          git pull origin main
          
          source /home/ubuntu/wplnnewscast/venv/bin/activate
          pip install -r requirements.txt

          sudo systemctl restart wplnnewscast
          sudo systemctl restart nginx
        EOF
